defaults: &defaults  
  site_name: xiaomajj
  
development:  
  <<: *defaults  
  domain: http://xiaomajijing.xiaoma.com 
  static_domain: http://xmjj.xiaoma.com
  
test:  
  <<: *defaults  
  domain: http://xiaomajijing.xiaoma.com 
  static_domain: http://xmjj.xiaoma.com
  
production:  
  <<: *defaults 
  domain: http://xiaomajijing.xiaoma.com 
  static_domain: http://xmjj.xiaoma.com

