defaults: &defaults  
  site_name: xiaomajj
  
development:  
  <<: *defaults  
  domain: http://192.168.1.230:4000
  
test:  
  <<: *defaults  
  domain: http://192.168.1.230:4000
  
production:  
  <<: *defaults 
  domain: http://xiaomajijing.xiaoma.com 

